# Generated by Django 2.1.7 on 2019-03-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
