# Generated by Django 2.1.7 on 2019-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtag_click_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='博客点击数'),
        ),
    ]
