# Generated by Django 2.1.7 on 2019-03-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_click_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Tag',
            new_name='tag',
        ),
    ]
